version: 1
formatters:
  brief:
    format: '%(asctime)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
    level: INFO
root:
  handlers: [console]
  level: INFO
